# Generated by Django 5.0.2 on 2024-02-19 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargaHorariaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.diadasemana')),
                ('horas', models.ManyToManyField(to='sistema.hora')),
            ],
        ),
        migrations.CreateModel(
            name='CargaHorariaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.diadasemana')),
                ('horas', models.ManyToManyField(to='sistema.hora')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('carga_horaria_semanal', models.ManyToManyField(related_name='carga_horaria', through='sistema.CargaHorariaProfessor', to='sistema.diadasemana')),
            ],
        ),
        migrations.AddField(
            model_name='cargahorariaprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professor'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tutor', models.CharField(blank=True, max_length=100)),
                ('carga_horaria_semanal', models.ManyToManyField(related_name='carga_horaria_turma', through='sistema.CargaHorariaTurma', to='sistema.diadasemana')),
            ],
        ),
        migrations.AddField(
            model_name='cargahorariaturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.turma'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('turmas', models.ManyToManyField(related_name='alunos', to='sistema.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.diadasemana')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.hora')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.turma')),
            ],
            options={
                'unique_together': {('dia_semana', 'hora', 'professor', 'turma')},
            },
        ),
    ]
