# Generated by Django 5.0.2 on 2024-02-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_aula_dia_semana_alter_aula_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.diadasemana'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.hora'),
        ),
        migrations.AlterField(
            model_name='diadasemana',
            name='nome',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hora',
            name='horario',
            field=models.TimeField(blank=True, null=True, unique=True),
        ),
    ]
