# Generated by Django 5.0.2 on 2024-02-22 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_aluno_id_alter_aula_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
