# Generated by Django 5.0.2 on 2024-02-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_aula_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='created_by',
        ),
    ]
